services:
  ollama:
    image: ollama/ollama
    volumes:
      - ./models:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  frontend:
    image: 192.168.1.10:5000/pazia-front

    ports:
      - "7856:3000"
    environment:
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
    depends_on:
      - ollama
    restart: unless-stopped